In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [18]:
trash_report = pd.read_csv('../data/trash_hauler_report.csv')

In [19]:
trash_report['Request '].value_counts()

Request
Trash - Curbside/Alley Missed Pickup    15028
Trash - Backdoor                         2629
Trash Collection Complaint               2312
Damage to Property                        257
Name: count, dtype: int64

In [20]:
trash_report['Trash Hauler'].value_counts()

Trash Hauler
RED RIVER    14395
METRO         3512
WASTE IND     1350
Metro           68
Name: count, dtype: int64

In [21]:
trash_report['Incident Address'].head()

0           3817 Crouch Dr
1    4028 Clarksville Pike
2      6528 Thunderbird Dr
3     2603 old matthews rd
4            604 croley dr
Name: Incident Address, dtype: object

In [22]:
trash_report['address_clean'] = trash_report['Incident Address'].str.split(',', expand=True)[0]

In [23]:
trash_report['address_clean'] = trash_report['address_clean'].str.title()

In [24]:
trash_report['address_clean'] = (trash_report['address_clean']
    .str.replace('Drive', 'Dr')
    .str.replace('Street', 'St')
    .str.replace('Road', 'Rd')
    .str.replace('Avenue', 'Ave')
    .str.replace('Boulevard', 'Blvd')
    .str.replace('Court', 'Ct')
    .str.replace('Lane', 'Ln')
    .str.replace('Place', 'Pl'))

In [25]:
trash_report['address_clean'].head(50)

0                    3817 Crouch Dr
1             4028 Clarksville Pike
2               6528 Thunderbird Dr
3              2603 Old Matthews Rd
4                     604 Croley Dr
5                    3602 Floral Dr
6                  4721 Chalmers Dr
7              1816 Jo Johnston Ave
8     4484 Lavergne Couchville Pike
9                   1206 Ireland St
10              3113 Hydes Ferry Rd
11           3210 Whites Creek Pike
12                  830 Meridian St
13                    2200 Osage St
14              6543 Thunderbird Dr
15            2218 Buena Vista Pike
16                2720 Riverbend Dr
17                 4209 Lone Oak Rd
18                  356 Kingview Dr
19                  449 Westboro Dr
20            1414 Old Hickory Blvd
21                 117 Lafayette Ct
22                1904 Meharry Blvd
23                  1144 Sewanee Rd
24               1815 Woodmont Blvd
25                      405 Page Rd
26                    4722 Danby Dr
27                  2812 27Th Ave S
28                  4506 Dakota Ave
29                  259 Sunrise Ave
30                  4311 Dakota Ave
31                  4029 Graybar Ct
32                   524 Harding Pl
33                    3702 Hobbs Rd
34              405 Brook Hollow Rd
35                 162 Antioch Pike
36                      131 Page Rd
37                    3704 Hobbs Rd
38           6011 Jocelyn Hollow Rd
39                  2524 Batavia St
40                   934 Battery Ln
41                  305 Williams Ct
42                      346 Lynn Dr
43                  4205 Arundel Ct
44               204 Channelkirk Ln
45               200 Channelkirk Ln
46                  4311 Dakota Ave
47             101 Westover Park Ct
48               201 Channelkirk Ln
49               205 Channelkirk Ln
Name: address_clean, dtype: object

In [26]:
trash_report['Trash Hauler'] = trash_report['Trash Hauler'].str.upper()

In [28]:
trash_report['Request '].value_counts()

Request
Trash - Curbside/Alley Missed Pickup    15028
Trash - Backdoor                         2629
Trash Collection Complaint               2312
Damage to Property                        257
Name: count, dtype: int64

In [29]:
missed_pickups = trash_report[trash_report['Request '] == 'Trash - Curbside/Alley Missed Pickup']

In [30]:
missed_pickups

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,address_clean
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1721259.366,685444.7996,4028 Clarksville Pike
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1707026.753,659887.4716,6528 Thunderbird Dr
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1735691.771,685027.2459,2603 Old Matthews Rd
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1710185.772,664205.1011,604 Croley Dr
8,25330,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed.,4484 Lavergne Couchville Pike,37013.0,RED RIVER,4210,33.0,1794533.514,618749.3427,4484 Lavergne Couchville Pike
...,...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/1/2019,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1781137.263,632448.5511,2731 Murfreesboro Pike
20222,267126,11/1/2019,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206.0,METRO,9508,6.0,1749711.399,669201.6016,1621 Long Ave
20223,267130,11/1/2019,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1770293.388,674936.3038,2943 Windemere Cir
20224,267134,11/1/2019,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1785224.998,627146.4002,3325 Murfreesboro Pike
20225,267137,11/1/2019,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1781360.323,637742.0068,604 Somerset Ct

In [36]:
missed_pickups[['address_clean' , 'Trash Hauler']].value_counts() > 1

address_clean             Trash Hauler
12546 Old Hickory Blvd    RED RIVER        True
1584 Bell Rd              RED RIVER        True
320 Old Hickory Blvd      RED RIVER        True
5135 Hickory Hollow Pkwy  RED RIVER        True
1816 Jo Johnston Ave      METRO            True
                                          ...
2604 Edge O Lake Dr       RED RIVER       False
2603 Ravine Dr            RED RIVER       False
2603 Old Matthews Rd      WASTE IND       False
2602 Oakwood Ave          METRO           False
Westboro Dr               RED RIVER       False
Name: count, Length: 9977, dtype: bool

In [37]:
missed_pickups_counts = missed_pickups[['address_clean', 'Trash Hauler']].value_counts()
missed_pickups

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,address_clean
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1721259.366,685444.7996,4028 Clarksville Pike
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1707026.753,659887.4716,6528 Thunderbird Dr
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1735691.771,685027.2459,2603 Old Matthews Rd
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1710185.772,664205.1011,604 Croley Dr
8,25330,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed.,4484 Lavergne Couchville Pike,37013.0,RED RIVER,4210,33.0,1794533.514,618749.3427,4484 Lavergne Couchville Pike
...,...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/1/2019,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1781137.263,632448.5511,2731 Murfreesboro Pike
20222,267126,11/1/2019,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206.0,METRO,9508,6.0,1749711.399,669201.6016,1621 Long Ave
20223,267130,11/1/2019,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1770293.388,674936.3038,2943 Windemere Cir
20224,267134,11/1/2019,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1785224.998,627146.4002,3325 Murfreesboro Pike
20225,267137,11/1/2019,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1781360.323,637742.0068,604 Somerset Ct

In [40]:
missed_pickups_counts.sum()

np.int64(14420)

In [42]:
missed_pickups_df['fine_owed'] = (missed_pickups_df['missed_count']-1) *200

NameError: name 'missed_pickups_df' is not defined