In [142]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

%matplotlib inline

In [143]:
trash_report = pd.read_csv('../data/trash_hauler_report.csv')
trash_report

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207.0,RED RIVER,3205,2.0,1727970.412,686779.4781
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1721259.366,685444.7996
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1707026.753,659887.4716
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1735691.771,685027.2459
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1710185.772,664205.1011
...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/1/2019,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1781137.263,632448.5511
20222,267126,11/1/2019,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206.0,METRO,9508,6.0,1749711.399,669201.6016
20223,267130,11/1/2019,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1770293.388,674936.3038
20224,267134,11/1/2019,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1785224.998,627146.4002
20225,267137,11/1/2019,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1781360.323,637742.0068

In [144]:
trash_report.info()
trash_report.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20226 entries, 0 to 20225
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Request Number    20226 non-null  int64
 1   Date Opened       20226 non-null  object
 2   Request           20226 non-null  object
 3   Description       20195 non-null  object
 4   Incident Address  20217 non-null  object
 5   Zip Code          20151 non-null  float64
 6   Trash Hauler      19325 non-null  object
 7   Trash Route       19279 non-null  object
 8   Council District  20177 non-null  float64
 9   State Plan X      20198 non-null  float64
 10  State Plan Y      20198 non-null  float64
dtypes: float64(4), int64(1), object(6)
memory usage: 1.7+ MB

Request Number        int64
Date Opened          object
Request              object
Description          object
Incident Address     object
Zip Code            float64
Trash Hauler         object
Trash Route          object
Council District    float64
State Plan X        float64
State Plan Y        float64
dtype: object

In [145]:
trash_report.columns

Index(['Request Number', 'Date Opened', 'Request ', 'Description',
       'Incident Address', 'Zip Code', 'Trash Hauler', 'Trash Route',
       'Council District', 'State Plan X', 'State Plan Y'],
      dtype='object')

In [146]:
#Q1
trash_report['Request '].value_counts()

Request
Trash - Curbside/Alley Missed Pickup    15028
Trash - Backdoor                         2629
Trash Collection Complaint               2312
Damage to Property                        257
Name: count, dtype: int64

In [147]:
#Q2
trash_report['Trash Hauler'].value_counts()

Trash Hauler
RED RIVER    14395
METRO         3512
WASTE IND     1350
Metro           68
Name: count, dtype: int64

In [148]:
trash_report['Incident Address'].head(20)

0                    3817 Crouch Dr
1             4028 Clarksville Pike
2               6528 Thunderbird Dr
3              2603 old matthews rd
4                     604 croley dr
5                    3602 floral dr
6                  4721 Chalmers Dr
7              1816 Jo Johnston Ave
8     4484 Lavergne Couchville Pike
9                   1206 Ireland St
10              3113 HYDES FERRY RD
11           3210 Whites Creek Pike
12                  830 Meridian St
13                    2200 osage st
14              6543 Thunderbird Dr
15            2218 BUENA VISTA PIKE
16                2720 riverbend dr
17                 4209 Lone Oak Rd
18                  356 Kingview Dr
19                  449 Westboro Dr
Name: Incident Address, dtype: object

In [149]:
trash_report['address_clean'] = trash_report['Incident Address'].str.split(',', expand=True)[0]

In [150]:
trash_report['address_clean'] = trash_report['address_clean'].str.title()

In [151]:
trash_report['address_clean'] = (trash_report['address_clean']
    .str.replace('Drive', 'Dr')
    .str.replace('Street', 'St')
    .str.replace('Road', 'Rd')
    .str.replace('Avenue', 'Ave')
    .str.replace('Boulevard', 'Blvd')
    .str.replace('Court', 'Ct')
    .str.replace('Lane', 'Ln')
    .str.replace('Place', 'Pl'))

In [152]:
trash_report[['Incident Address', 'address_clean']].head(20)

                 Incident Address                  address_clean
0                  3817 Crouch Dr                 3817 Crouch Dr
1           4028 Clarksville Pike          4028 Clarksville Pike
2             6528 Thunderbird Dr            6528 Thunderbird Dr
3            2603 old matthews rd           2603 Old Matthews Rd
4                   604 croley dr                  604 Croley Dr
5                  3602 floral dr                 3602 Floral Dr
6                4721 Chalmers Dr               4721 Chalmers Dr
7            1816 Jo Johnston Ave           1816 Jo Johnston Ave
8   4484 Lavergne Couchville Pike  4484 Lavergne Couchville Pike
9                 1206 Ireland St                1206 Ireland St
10            3113 HYDES FERRY RD            3113 Hydes Ferry Rd
11         3210 Whites Creek Pike         3210 Whites Creek Pike
12                830 Meridian St                830 Meridian St
13                  2200 osage st                  2200 Osage St
14            6543 Thunderbird Dr            6543 Thunderbird Dr
15          2218 BUENA VISTA PIKE          2218 Buena Vista Pike
16              2720 riverbend dr              2720 Riverbend Dr
17               4209 Lone Oak Rd               4209 Lone Oak Rd
18                356 Kingview Dr                356 Kingview Dr
19                449 Westboro Dr                449 Westboro Dr

In [153]:
trash_report['Trash Hauler'] = trash_report['Trash Hauler'].str.upper()
trash_report['Trash Hauler'].value_counts()

Trash Hauler
RED RIVER    14395
METRO         3580
WASTE IND     1350
Name: count, dtype: int64

In [154]:
trash_report['Date Opened'] = pd.to_datetime(trash_report['Date Opened'], format='%m/%d/%Y')

In [155]:
trash_report.dtypes

Request Number               int64
Date Opened         datetime64[ns]
Request                     object
Description                 object
Incident Address            object
Zip Code                   float64
Trash Hauler                object
Trash Route                 object
Council District           float64
State Plan X               float64
State Plan Y               float64
address_clean               object
dtype: object

In [156]:
missed_pickups = trash_report[trash_report['Request '] == 'Trash - Curbside/Alley Missed Pickup']
missed_pickups

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,address_clean
1,25274,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1721259.366,685444.7996,4028 Clarksville Pike
2,25276,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1707026.753,659887.4716,6528 Thunderbird Dr
3,25307,2017-11-01,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1735691.771,685027.2459,2603 Old Matthews Rd
4,25312,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1710185.772,664205.1011,604 Croley Dr
8,25330,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed.,4484 Lavergne Couchville Pike,37013.0,RED RIVER,4210,33.0,1794533.514,618749.3427,4484 Lavergne Couchville Pike
...,...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,2019-11-01,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1781137.263,632448.5511,2731 Murfreesboro Pike
20222,267126,2019-11-01,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206.0,METRO,9508,6.0,1749711.399,669201.6016,1621 Long Ave
20223,267130,2019-11-01,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1770293.388,674936.3038,2943 Windemere Cir
20224,267134,2019-11-01,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1785224.998,627146.4002,3325 Murfreesboro Pike
20225,267137,2019-11-01,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1781360.323,637742.0068,604 Somerset Ct

In [157]:
missed_pickups_counts = missed_pickups[['address_clean', 'Trash Hauler']].value_counts()
missed_pickups_counts

address_clean             Trash Hauler
12546 Old Hickory Blvd    RED RIVER       21
1584 Bell Rd              RED RIVER       18
320 Old Hickory Blvd      RED RIVER       17
5135 Hickory Hollow Pkwy  RED RIVER       17
1816 Jo Johnston Ave      METRO           17
                                          ..
2604 Edge O Lake Dr       RED RIVER        1
2603 Ravine Dr            RED RIVER        1
2603 Old Matthews Rd      WASTE IND        1
2602 Oakwood Ave          METRO            1
Westboro Dr               RED RIVER        1
Name: count, Length: 9977, dtype: int64

In [158]:
missed_pickups_df = missed_pickups_counts.reset_index()
missed_pickups_df.columns = ['address_clean', 'Trash Hauler', 'missed_count']
missed_pickups_df.head()

              address_clean Trash Hauler  missed_count
0    12546 Old Hickory Blvd    RED RIVER            21
1              1584 Bell Rd    RED RIVER            18
2      320 Old Hickory Blvd    RED RIVER            17
3  5135 Hickory Hollow Pkwy    RED RIVER            17
4      1816 Jo Johnston Ave        METRO            17

In [159]:
counts = missed_pickups_df['address_clean'].value_counts()
multi_hauler_addresses = counts[counts > 1].index

missed_pickups_df.query('address_clean in @multi_hauler_addresses')

       address_clean Trash Hauler  missed_count
825   909 46Th Ave N    RED RIVER             3
2108  109 Chetopa Ct    RED RIVER             2
4283  909 46Th Ave N        METRO             1
6802  109 Chetopa Ct        METRO             1

In [160]:
missed_pickups_df['fine_owed'] = (missed_pickups_df['missed_count'] - 1) * 200
missed_pickups.head(10)

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,address_clean
1,25274,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1721259.366,685444.7996,4028 Clarksville Pike
2,25276,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1707026.753,659887.4716,6528 Thunderbird Dr
3,25307,2017-11-01,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1735691.771,685027.2459,2603 Old Matthews Rd
4,25312,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1710185.772,664205.1011,604 Croley Dr
8,25330,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed.,4484 Lavergne Couchville Pike,37013.0,RED RIVER,4210,33.0,1794533.514,618749.3427,4484 Lavergne Couchville Pike
9,25331,2017-11-01,Trash - Curbside/Alley Missed Pickup,"Trash missed Tuesday again, ALLEY",1206 Ireland St,37208.0,METRO,9208,19.0,1733029.474,668762.6409,1206 Ireland St
10,25341,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed trash pickup - resident has at curb for...,3113 HYDES FERRY RD,37218.0,RED RIVER,4204,2.0,1721577.768,676018.3999,3113 Hydes Ferry Rd
12,25359,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed. Does not have access to alley.,830 Meridian St,37207.0,METRO,9207,5.0,1741744.712,675328.6661,830 Meridian St
14,25370,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed.,6543 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1706941.584,659614.1836,6543 Thunderbird Dr
15,25371,2017-11-01,Trash - Curbside/Alley Missed Pickup,Pickup missed,2218 BUENA VISTA PIKE,37218.0,RED RIVER,4204,2.0,1724505.766,679777.5997,2218 Buena Vista Pike

In [161]:
missed_pickups_df.dtypes

address_clean    object
Trash Hauler     object
missed_count      int64
fine_owed         int64
dtype: object

In [162]:
missed_pickups_by_hauler = (missed_pickups_df.groupby('Trash Hauler')['fine_owed'].agg(['sum']))
missed_pickups_by_hauler

                 sum
Trash Hauler
METRO         166000
RED RIVER     660200
WASTE IND      62400

In [163]:
missed_pickups_by_hauler = missed_pickups_by_hauler.reset_index()
missed_pickups_by_hauler.columns = ['Trash Hauler', 'total_fine_owed']
missed_pickups_by_hauler

  Trash Hauler  total_fine_owed
0        METRO           166000
1    RED RIVER           660200
2    WASTE IND            62400

In [164]:
#Q3
missed_pickups_by_hauler = missed_pickups_by_hauler.sort_values(by='total_fine_owed', ascending=False)
missed_pickups_by_hauler

  Trash Hauler  total_fine_owed
1    RED RIVER           660200
0        METRO           166000
2    WASTE IND            62400

In [ ]:
#TOTAL FINES: $888,600
#ADD YELP REVIEWS